### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by bicho19** [jiangchao87/ParseGPTBin#1]
Hello!

I used your script on github but everytime it gives me an error .

Traceback (most recent call last):
  File "C:/Users/monLenovo/Downloads/ParseGPT-master/parsegpt.py", line 819, in <module>
    ParseGPT()                   ## automatically parses GPTFile
  File "C:/Users/monLenovo/Downloads/ParseGPT-master/parsegpt.py", line 697, in ParseGPT
    PrimaryGPT[i] = ord(tempfile[i])
IndexError: list assignment index out of range

Please help us fix the problem because many users are depending on it.

Many users on the internet bricked their LG G Flex 2 and there is no way to unbrick it but there is a good change with your tool if it work correctly with the primaryGPT.bin from the extract ROM of G Flex 2.

**Comment by KieranFoot** [comment]
I have the same issue here.

Fixed this by making sure the input file is only 17408 Bytes (34x512 Blocks)

**Comment by nj8u7cc** [comment]
@bicho19  
As @kieranfoot   mentioned, please make sure that your input file is 17408 bytes,cause 
`PrimaryGPT = [0]*34*512  # This is LBA 0 to 33 (34 sectors total)    (start of disk)`
You can use any hex editor to cut off redundant bytes

Ps:
I wrote this py based on the PartitioningTool.py in QC's compile toolchain a year ago, so I don't know if it would work correctly in your phone. If you have any question, just contact me

**Comment by harissiddiq** [comment]
the tool work fine but i have question .the new maingpt.bin and backup have same address like gpt.bin ???and how i could generate patch.xml ?? without that partition not work
